### ISSUE TITLE
Removal of ez_setup

### ISSUE THREAD

**Issue by mariusvniekerk** [Preston-Landers/concurrent-log-handler#30]
Perhaps its time to just make this a regular setuptools/pip buildable thing without relying on vendoring ez_setup?

**Comment by Preston-Landers** [comment]
To be honest I'm not sure what the impact of this might be. As far as I can gather, ez_setup.py is needed for Python 2.4 / 2.5 in order to use setuptools. This package only claims to support Python 2.6 or higher, so I suppose it should be fine to remove this legacy code. Does the presence of ez_setup cause any other sort of problem?

**Comment by mariusvniekerk** [comment]
I did this as part of packaging it on conda-forge here https://github.com/conda-forge/staged-recipes/pull/12682

Sadly the logs for the failed builds are no longer available.   If I recall the issues were that it actively downloads some very old versions of distutils using http not https urls and that modern versions of the python setup stack disallows non https pieces.
