### ISSUE TITLE
Does below issue has been fixed?

### ISSUE THREAD

**Issue by onkar6699** [Preston-Landers/concurrent-log-handler#44]
https://bugs.launchpad.net/python-concurrent-log-handler/+bug/1265150

**Comment by Preston-Landers** [comment]
Should be, yeah. That bug was one of the reasons I forked that package here.

**Comment by onkar6699** [comment]
@Preston-Landers might be a basic question I am  asking
__init__.py file which uses stream & locks for logging right?
if we want to use queue handler & listener then need to use setup_logging_queues()?
which gives better performance by using queues or streams?

**Comment by Preston-Landers** [comment]
The basic class in `__init__.py` is purely synchronous. That is, when you make a log call from your app's code, your app's logic suspends and waits until the log call is fully complete, including any (relatively slow) file rotation that needed to happen. 

Optionally you can add async behavior with `setup_logging_queues`, so that a log call puts the logging request on a queue for another thread to handle while your app can continue on. (However when you do this, your app has no way to know when or if the log call actually completed.) Whether the queue helps or hurts performance is highly dependent on a number of factors including the frequency and complexity of logging calls. Probably doesn't hurt to evaluate it both ways.

You might want to check the example code if you haven't already.

https://github.com/Preston-Landers/concurrent-log-handler/blob/master/src/example.py

**Comment by onkar6699** [comment]
@Preston-Landers As in this library According to the instructions at "https://github.com/Preston-Landers/concurrent-log-handler#important-requirements", each process must create a separate instance of ConcurrentRotatingFileHandler
But since we use --preload when starting gunicorn, the initialization code here is run before the worker processes are created. That would mean the processes end up sharing this object. would that impact?

**Comment by Preston-Landers** [comment]
I'm not all that familiar with gunicorn but it appears to use POSIX/Linux fork. 

The wording was perhaps unclear there. Mainly it means that you can't serialize or pass a CRFH object across a socket connection. For instance, with the non-fork start methods in the "multiprocessing" module.

The readme also says a little further down:
If your app uses fork() then this may not apply; child processes of a fork() should be able to inherit the object instance.

**Comment by onkar6699** [comment]
@Preston-Landers what installation name should I use
pip3 install concurrent_log_handler or
pip3 install concurrent-log-handler
?

**Comment by Preston-Landers** [comment]
The pip name is `concurrent-log-handler`

https://pypi.org/project/concurrent-log-handler/

The actual Python package (import) name has underscores.
